"""initial schema: customers, documents, document_customers, recommendations

Revision ID: 1354c157c9a1
Revises: 
Create Date: 2026-07-13 21:29:33.045747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1354c157c9a1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customers_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_postal_code'), ['postal_code'], unique=False)

    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('doc_type', sa.Enum('LEIPZIGER_LISTE', 'HUK_LISTE', 'GUTACHTEN', 'RECHNUNG', 'VERSICHERUNGSUNTERLAGEN', 'SCHADENAKTE', 'BRIEF', 'SONSTIGES', name='doctype'), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'OCR_PROCESSING', 'OCR_DONE', 'AI_PROCESSING', 'DONE', 'FAILED', name='docstatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('ocr_engine_used', sa.Enum('NONE', 'TESSERACT', 'VISION', name='ocrengine'), nullable=False),
    sa.Column('ocr_confidence', sa.Float(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('raw_json', sa.JSON(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('vehicle', sa.String(length=255), nullable=True),
    sa.Column('license_plate', sa.String(length=20), nullable=True),
    sa.Column('insurer', sa.String(length=255), nullable=True),
    sa.Column('contract_number', sa.String(length=100), nullable=True),
    sa.Column('case_number', sa.String(length=100), nullable=True),
    sa.Column('broker', sa.String(length=255), nullable=True),
    sa.Column('contract_start_date', sa.Date(), nullable=True),
    sa.Column('products', sa.JSON(), nullable=True),
    sa.Column('special_notes', sa.Text(), nullable=True),
    sa.Column('is_neugeschaeft', sa.Boolean(), nullable=True),
    sa.Column('is_fahrzeugwechsel', sa.Boolean(), nullable=True),
    sa.Column('is_angebot', sa.Boolean(), nullable=True),
    sa.Column('cross_sell_opportunity', sa.Boolean(), nullable=True),
    sa.Column('has_multiple_products', sa.Boolean(), nullable=True),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='priority'), nullable=True),
    sa.Column('recommended_next_action', sa.String(length=255), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_doc_type'), ['doc_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_license_plate'), ['license_plate'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_status'), ['status'], unique=False)

    op.create_table('document_customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('row_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'customer_id', name='uq_document_customer')
    )
    with op.batch_alter_table('document_customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_customers_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_customers_document_id'), ['document_id'], unique=False)

    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('CALL_TODAY', 'PRIORITIZE_VEHICLE_CHANGE', 'OFFER_LEGAL_PROTECTION', 'OFFER_HOUSEHOLD_INSURANCE', 'CHECK_ACCIDENT_INSURANCE', 'CHECK_SUPPLEMENTARY_HEALTH', 'OTHER', name='recommendationtype'), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='priority'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'DISMISSED', 'DONE', name='recommendationstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recommendations_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendations_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendations_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendations_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recommendations_status'))
        batch_op.drop_index(batch_op.f('ix_recommendations_priority'))
        batch_op.drop_index(batch_op.f('ix_recommendations_document_id'))
        batch_op.drop_index(batch_op.f('ix_recommendations_customer_id'))

    op.drop_table('recommendations')
    with op.batch_alter_table('document_customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_customers_document_id'))
        batch_op.drop_index(batch_op.f('ix_document_customers_customer_id'))

    op.drop_table('document_customers')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_status'))
        batch_op.drop_index(batch_op.f('ix_documents_priority'))
        batch_op.drop_index(batch_op.f('ix_documents_license_plate'))
        batch_op.drop_index(batch_op.f('ix_documents_doc_type'))
        batch_op.drop_index(batch_op.f('ix_documents_customer_id'))

    op.drop_table('documents')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_postal_code'))
        batch_op.drop_index(batch_op.f('ix_customers_name'))
        batch_op.drop_index(batch_op.f('ix_customers_city'))

    op.drop_table('customers')
    # ### end Alembic commands ###
