"""M13 list_scope auf Document

Revision ID: 84dc72643881
Revises: c7274613e41d
Create Date: 2026-07-18 20:00:21.187412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84dc72643881'
down_revision = 'c7274613e41d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('list_scope', sa.Enum('OWN', 'GESCHAEFTSSTELLE', name='listscope'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_column('list_scope')

    # ### end Alembic commands ###
