"""add vermittlernummer to users

Revision ID: 92ce8e92157e
Revises: 4a72fc4ca2f7
Create Date: 2026-07-14 19:25:28.864480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92ce8e92157e'
down_revision = '4a72fc4ca2f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vermittlernummer', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_vermittlernummer'), ['vermittlernummer'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_vermittlernummer'))
        batch_op.drop_column('vermittlernummer')

    # ### end Alembic commands ###
