"""M11 Aufgaben, Wiedervorlagen, Listenvergleich, Kundenchronik

Revision ID: aff0bcca10b2
Revises: 92ce8e92157e
Create Date: 2026-07-15 08:02:54.637702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aff0bcca10b2'
down_revision = '92ce8e92157e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('list_comparisons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('previous_document_id', sa.Integer(), nullable=True),
    sa.Column('compared_at', sa.DateTime(), nullable=True),
    sa.Column('new_customer_count', sa.Integer(), nullable=False),
    sa.Column('new_contract_count', sa.Integer(), nullable=False),
    sa.Column('new_offer_count', sa.Integer(), nullable=False),
    sa.Column('status_change_count', sa.Integer(), nullable=False),
    sa.Column('storno_count', sa.Integer(), nullable=False),
    sa.Column('removed_customer_count', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['previous_document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('list_comparisons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_list_comparisons_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_list_comparisons_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('list_comparison_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('list_comparison_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('change_type', sa.Enum('NEW_CUSTOMER', 'NEW_CONTRACT', 'NEW_OFFER', 'STATUS_CHANGE', 'STORNO', 'REMOVED_CUSTOMER', name='listchangetype'), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['list_comparison_id'], ['list_comparisons.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('list_comparison_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_list_comparison_entries_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_list_comparison_entries_list_comparison_id'), ['list_comparison_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_list_comparison_entries_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('recommendation_id', sa.Integer(), nullable=True),
    sa.Column('assigned_user_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('CALL_TODAY', 'FOLLOW_UP_OFFER', 'REQUEST_DOCUMENTS', 'PREPARE_CONTRACT', 'CHECK_CLOSURE', 'SCHEDULE_APPOINTMENT', 'OTHER', name='tasktype'), nullable=False),
    sa.Column('wiedervorlage_reason', sa.Enum('OFFER_OLDER_THAN_7_DAYS', 'OFFER_OLDER_THAN_14_DAYS', 'NO_RESPONSE', 'MISSING_DOCUMENTS', 'OPEN_CLOSURE', name='wiedervorlagereason'), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='priority'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'DONE', 'DISMISSED', name='taskstatus'), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_assigned_user_id'), ['assigned_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_recommendation_id'), ['recommendation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('customer_timeline_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.Enum('DOCUMENT_UPLOADED', 'OFFER_DETECTED', 'NEW_CONTRACT_DETECTED', 'VEHICLE_CHANGE_DETECTED', 'STORNO_DETECTED', 'TASK_CREATED', 'TASK_STATUS_CHANGED', 'LIST_COMPARISON_CHANGE', name='timelineeventtype'), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customer_timeline_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_timeline_events_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_timeline_events_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_timeline_events_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_user_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_customers_assigned_user_id'), ['assigned_user_id'], unique=False)
        batch_op.create_foreign_key('fk_customers_assigned_user_id_users', 'users', ['assigned_user_id'], ['id'])

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_storno', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('uploaded_by_user_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_documents_uploaded_by_user_id'), ['uploaded_by_user_id'], unique=False)
        batch_op.create_foreign_key('fk_documents_uploaded_by_user_id_users', 'users', ['uploaded_by_user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_constraint('fk_documents_uploaded_by_user_id_users', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_documents_uploaded_by_user_id'))
        batch_op.drop_column('uploaded_by_user_id')
        batch_op.drop_column('is_storno')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_constraint('fk_customers_assigned_user_id_users', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_customers_assigned_user_id'))
        batch_op.drop_column('assigned_user_id')

    with op.batch_alter_table('customer_timeline_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_timeline_events_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_customer_timeline_events_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_customer_timeline_events_customer_id'))

    op.drop_table('customer_timeline_events')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_tasks_recommendation_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_priority'))
        batch_op.drop_index(batch_op.f('ix_tasks_due_date'))
        batch_op.drop_index(batch_op.f('ix_tasks_document_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_customer_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_assigned_user_id'))

    op.drop_table('tasks')
    with op.batch_alter_table('list_comparison_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_list_comparison_entries_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_list_comparison_entries_list_comparison_id'))
        batch_op.drop_index(batch_op.f('ix_list_comparison_entries_customer_id'))

    op.drop_table('list_comparison_entries')
    with op.batch_alter_table('list_comparisons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_list_comparisons_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_list_comparisons_document_id'))

    op.drop_table('list_comparisons')
    # ### end Alembic commands ###
