"""M12 Analyse-Engine: AnalysisRun, RecommendationFeedback, neue Felder

Revision ID: c7274613e41d
Revises: aff0bcca10b2
Create Date: 2026-07-15 09:53:21.379532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7274613e41d'
down_revision = 'aff0bcca10b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('engine_version', sa.String(length=50), nullable=False),
    sa.Column('prompt_version', sa.String(length=50), nullable=False),
    sa.Column('openai_model', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('RUNNING', 'SUCCEEDED', 'FAILED', name='analysisrunstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('stage_durations', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('overall_confidence', sa.Float(), nullable=True),
    sa.Column('summary', sa.JSON(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analysis_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysis_runs_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_runs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_runs_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('recommendation_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('rated_by_user_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Enum('UP', 'DOWN', name='feedbackrating'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rated_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recommendation_feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recommendation_feedback_rated_by_user_id'), ['rated_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendation_feedback_task_id'), ['task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendation_feedback_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('document_customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('field_confidence', sa.JSON(), nullable=True))

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('broker_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('product_line', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('premium', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('tariff', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('field_confidence', sa.JSON(), nullable=True))
        batch_op.create_index(batch_op.f('ix_documents_product_line'), ['product_line'], unique=False)

    with op.batch_alter_table('list_comparisons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('new_product_line_count', sa.Integer(), nullable=False))

    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('explanation', sa.Text(), nullable=True))
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=26),
               type_=sa.Enum('CALL_TODAY', 'PRIORITIZE_VEHICLE_CHANGE', 'OFFER_LEGAL_PROTECTION', 'OFFER_HOUSEHOLD_INSURANCE', 'CHECK_ACCIDENT_INSURANCE', 'CHECK_SUPPLEMENTARY_HEALTH', 'OTHER', 'CROSS_SELL_HOUSEHOLD_FROM_BUILDING', 'CROSS_SELL_LIABILITY_FROM_VEHICLE', 'SALES_RISK_MULTIPLE_OFFERS_NO_CLOSURE', 'HIGH_PRIORITY_STORNO', name='recommendationtype'),
               existing_nullable=False)

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('explanation', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('explanation')

    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.Enum('CALL_TODAY', 'PRIORITIZE_VEHICLE_CHANGE', 'OFFER_LEGAL_PROTECTION', 'OFFER_HOUSEHOLD_INSURANCE', 'CHECK_ACCIDENT_INSURANCE', 'CHECK_SUPPLEMENTARY_HEALTH', 'OTHER', 'CROSS_SELL_HOUSEHOLD_FROM_BUILDING', 'CROSS_SELL_LIABILITY_FROM_VEHICLE', 'SALES_RISK_MULTIPLE_OFFERS_NO_CLOSURE', 'HIGH_PRIORITY_STORNO', name='recommendationtype'),
               type_=sa.VARCHAR(length=26),
               existing_nullable=False)
        batch_op.drop_column('explanation')

    with op.batch_alter_table('list_comparisons', schema=None) as batch_op:
        batch_op.drop_column('new_product_line_count')

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_product_line'))
        batch_op.drop_column('field_confidence')
        batch_op.drop_column('tariff')
        batch_op.drop_column('premium')
        batch_op.drop_column('product_line')
        batch_op.drop_column('broker_number')

    with op.batch_alter_table('document_customers', schema=None) as batch_op:
        batch_op.drop_column('field_confidence')

    with op.batch_alter_table('recommendation_feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recommendation_feedback_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_recommendation_feedback_task_id'))
        batch_op.drop_index(batch_op.f('ix_recommendation_feedback_rated_by_user_id'))

    op.drop_table('recommendation_feedback')
    with op.batch_alter_table('analysis_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_runs_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_analysis_runs_status'))
        batch_op.drop_index(batch_op.f('ix_analysis_runs_document_id'))

    op.drop_table('analysis_runs')
    # ### end Alembic commands ###
